export const START_FETCHING_LIST_ITEM = 'features/AddOn/START_FETCHING_LIST_ITEM';
export const ERROR_FETCHING_LIST_ITEM = 'features/AddOn/ERROR_FETCHING_LIST_ITEM';
export const SUCCESS_FETCHING_LIST_ITEM = 'features/AddOn/SUCCESS_FETCHING_LIST_ITEM';
